# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/paulinet',
                'doc_host': 'https://xrsrke.github.io',
                'git_url': 'https://github.com/xrsrke/paulinet',
                'lib_path': 'paulinet'},
  'syms': {'paulinet.core': {'paulinet.core.foo': ('core.html#foo', 'paulinet/core.py')}}}
